// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.2
// source: phrase.proto

package phrasev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Phrase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text    string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	UserId  string `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	StoryId string `protobuf:"bytes,4,opt,name=storyId,proto3" json:"storyId,omitempty"`
}

func (x *Phrase) Reset() {
	*x = Phrase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phrase_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Phrase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Phrase) ProtoMessage() {}

func (x *Phrase) ProtoReflect() protoreflect.Message {
	mi := &file_phrase_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Phrase.ProtoReflect.Descriptor instead.
func (*Phrase) Descriptor() ([]byte, []int) {
	return file_phrase_proto_rawDescGZIP(), []int{0}
}

func (x *Phrase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Phrase) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Phrase) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Phrase) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

type PhraseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PhraseRequest) Reset() {
	*x = PhraseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phrase_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhraseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhraseRequest) ProtoMessage() {}

func (x *PhraseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_phrase_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhraseRequest.ProtoReflect.Descriptor instead.
func (*PhraseRequest) Descriptor() ([]byte, []int) {
	return file_phrase_proto_rawDescGZIP(), []int{1}
}

func (x *PhraseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PhrasesByStoryIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phrases []*Phrase `protobuf:"bytes,1,rep,name=phrases,proto3" json:"phrases,omitempty"`
}

func (x *PhrasesByStoryIdResponse) Reset() {
	*x = PhrasesByStoryIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phrase_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhrasesByStoryIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhrasesByStoryIdResponse) ProtoMessage() {}

func (x *PhrasesByStoryIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_phrase_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhrasesByStoryIdResponse.ProtoReflect.Descriptor instead.
func (*PhrasesByStoryIdResponse) Descriptor() ([]byte, []int) {
	return file_phrase_proto_rawDescGZIP(), []int{2}
}

func (x *PhrasesByStoryIdResponse) GetPhrases() []*Phrase {
	if x != nil {
		return x.Phrases
	}
	return nil
}

type PhrasesByStoryIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoryId string `protobuf:"bytes,1,opt,name=storyId,proto3" json:"storyId,omitempty"`
}

func (x *PhrasesByStoryIdRequest) Reset() {
	*x = PhrasesByStoryIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phrase_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PhrasesByStoryIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhrasesByStoryIdRequest) ProtoMessage() {}

func (x *PhrasesByStoryIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_phrase_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhrasesByStoryIdRequest.ProtoReflect.Descriptor instead.
func (*PhrasesByStoryIdRequest) Descriptor() ([]byte, []int) {
	return file_phrase_proto_rawDescGZIP(), []int{3}
}

func (x *PhrasesByStoryIdRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

type AddPhraseToStoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phrase *Phrase `protobuf:"bytes,2,opt,name=phrase,proto3" json:"phrase,omitempty"`
}

func (x *AddPhraseToStoryRequest) Reset() {
	*x = AddPhraseToStoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phrase_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPhraseToStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPhraseToStoryRequest) ProtoMessage() {}

func (x *AddPhraseToStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_phrase_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPhraseToStoryRequest.ProtoReflect.Descriptor instead.
func (*AddPhraseToStoryRequest) Descriptor() ([]byte, []int) {
	return file_phrase_proto_rawDescGZIP(), []int{4}
}

func (x *AddPhraseToStoryRequest) GetPhrase() *Phrase {
	if x != nil {
		return x.Phrase
	}
	return nil
}

var File_phrase_proto protoreflect.FileDescriptor

var file_phrase_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x22, 0x5e, 0x0a, 0x06, 0x50, 0x68, 0x72, 0x61, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x22, 0x1f, 0x0a, 0x0d, 0x50, 0x68, 0x72, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x44, 0x0a, 0x18, 0x50, 0x68, 0x72, 0x61, 0x73,
	0x65, 0x73, 0x42, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x2e, 0x50, 0x68,
	0x72, 0x61, 0x73, 0x65, 0x52, 0x07, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x73, 0x22, 0x33, 0x0a,
	0x17, 0x50, 0x68, 0x72, 0x61, 0x73, 0x65, 0x73, 0x42, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x49, 0x64, 0x22, 0x41, 0x0a, 0x17, 0x41, 0x64, 0x64, 0x50, 0x68, 0x72, 0x61, 0x73, 0x65, 0x54,
	0x6f, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a,
	0x06, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x2e, 0x50, 0x68, 0x72, 0x61, 0x73, 0x65, 0x52, 0x06, 0x70,
	0x68, 0x72, 0x61, 0x73, 0x65, 0x32, 0xa9, 0x02, 0x0a, 0x0d, 0x50, 0x68, 0x72, 0x61, 0x73, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x67, 0x65, 0x74, 0x50, 0x68,
	0x72, 0x61, 0x73, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x2e, 0x50, 0x68,
	0x72, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x70, 0x68,
	0x72, 0x61, 0x73, 0x65, 0x2e, 0x50, 0x68, 0x72, 0x61, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a,
	0x11, 0x67, 0x65, 0x74, 0x50, 0x68, 0x72, 0x61, 0x73, 0x65, 0x73, 0x42, 0x79, 0x53, 0x74, 0x6f,
	0x72, 0x79, 0x12, 0x1f, 0x2e, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x2e, 0x50, 0x68, 0x72, 0x61,
	0x73, 0x65, 0x73, 0x42, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x2e, 0x50, 0x68, 0x72,
	0x61, 0x73, 0x65, 0x73, 0x42, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0a, 0x61, 0x64, 0x64, 0x54, 0x6f,
	0x53, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x1f, 0x2e, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x2e, 0x41,
	0x64, 0x64, 0x50, 0x68, 0x72, 0x61, 0x73, 0x65, 0x54, 0x6f, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x2e,
	0x50, 0x68, 0x72, 0x61, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x10, 0x67, 0x65, 0x74, 0x50,
	0x68, 0x72, 0x61, 0x73, 0x65, 0x73, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1f, 0x2e, 0x70,
	0x68, 0x72, 0x61, 0x73, 0x65, 0x2e, 0x50, 0x68, 0x72, 0x61, 0x73, 0x65, 0x73, 0x42, 0x79, 0x53,
	0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e,
	0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x2e, 0x50, 0x68, 0x72, 0x61, 0x73, 0x65, 0x22, 0x00, 0x30,
	0x01, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x7a, 0x61, 0x6c, 0x68, 0x6f, 0x6e, 0x61, 0x6e, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x3b,
	0x70, 0x68, 0x72, 0x61, 0x73, 0x65, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_phrase_proto_rawDescOnce sync.Once
	file_phrase_proto_rawDescData = file_phrase_proto_rawDesc
)

func file_phrase_proto_rawDescGZIP() []byte {
	file_phrase_proto_rawDescOnce.Do(func() {
		file_phrase_proto_rawDescData = protoimpl.X.CompressGZIP(file_phrase_proto_rawDescData)
	})
	return file_phrase_proto_rawDescData
}

var file_phrase_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_phrase_proto_goTypes = []interface{}{
	(*Phrase)(nil),                   // 0: phrase.Phrase
	(*PhraseRequest)(nil),            // 1: phrase.PhraseRequest
	(*PhrasesByStoryIdResponse)(nil), // 2: phrase.PhrasesByStoryIdResponse
	(*PhrasesByStoryIdRequest)(nil),  // 3: phrase.PhrasesByStoryIdRequest
	(*AddPhraseToStoryRequest)(nil),  // 4: phrase.AddPhraseToStoryRequest
}
var file_phrase_proto_depIdxs = []int32{
	0, // 0: phrase.PhrasesByStoryIdResponse.phrases:type_name -> phrase.Phrase
	0, // 1: phrase.AddPhraseToStoryRequest.phrase:type_name -> phrase.Phrase
	1, // 2: phrase.PhraseService.getPhrase:input_type -> phrase.PhraseRequest
	3, // 3: phrase.PhraseService.getPhrasesByStory:input_type -> phrase.PhrasesByStoryIdRequest
	4, // 4: phrase.PhraseService.addToStory:input_type -> phrase.AddPhraseToStoryRequest
	3, // 5: phrase.PhraseService.getPhrasesStream:input_type -> phrase.PhrasesByStoryIdRequest
	0, // 6: phrase.PhraseService.getPhrase:output_type -> phrase.Phrase
	2, // 7: phrase.PhraseService.getPhrasesByStory:output_type -> phrase.PhrasesByStoryIdResponse
	0, // 8: phrase.PhraseService.addToStory:output_type -> phrase.Phrase
	0, // 9: phrase.PhraseService.getPhrasesStream:output_type -> phrase.Phrase
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_phrase_proto_init() }
func file_phrase_proto_init() {
	if File_phrase_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_phrase_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Phrase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phrase_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhraseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phrase_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhrasesByStoryIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phrase_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PhrasesByStoryIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phrase_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPhraseToStoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_phrase_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_phrase_proto_goTypes,
		DependencyIndexes: file_phrase_proto_depIdxs,
		MessageInfos:      file_phrase_proto_msgTypes,
	}.Build()
	File_phrase_proto = out.File
	file_phrase_proto_rawDesc = nil
	file_phrase_proto_goTypes = nil
	file_phrase_proto_depIdxs = nil
}
